import type { Metadata } from "next";
import { Luckiest_Guy } from "next/font/google";
import "./globals.css";

const danta = Luckiest_Guy({
  subsets: ["latin"],
  variables: "--font--luckiest-guy",
  weight: "400",

});

export const metadata: Metadata = {
  title: "1st Symphony",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={danta.className}>{children}</body>
    </html>
  );
}
