import type { Metadata } from "next";
import "../../styles/globals.css";
import React from "react";




export const metadata: Metadata = {
  title: "1st Symphony",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <head>
        <title>1st Symphony</title>
        
    </head>
    <body >
    {children}

    </body>
    </html>
  );
}
